services:
  - type: web
    name: stable-diffusion-webui-backend
    env: python
    plan: starter
    buildCommand: pip install --upgrade pip && pip install --no-cache-dir --timeout 300 --retries 3 -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PORT
        value: 10000
      - key: SD_WEBUI_RESTARTING
        value: "1"
      - key: GRADIO_SERVER_NAME
        value: "0.0.0.0"
      - key: GRADIO_SERVER_PORT
        value: "10000"
      - key: API_ONLY
        value: "true"
      - key: ENABLE_CORS
        value: "true"
      - key: ALLOW_ORIGINS
        value: "https://uwear-virtual-shop.onrender.com,http://localhost:3000,http://localhost:5173"
    healthCheckPath: /docs
    autoDeploy: true
